name: Deploy Azure Function via ZIP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Publish Azure Function with metadata
      run: |
        dotnet publish ./SedesFunction.csproj --configuration Release --output ./publish_output /p:GenerateEntryPointsForFunctionApp=true

    - name: Create ZIP for deployment
      run: |
        cd publish_output
        zip -r ../functionapp.zip .
        cd ..

    - name: Deploy to Azure Function App using ZIP Deploy
      run: |
        curl -X POST -u "${{ secrets.AZURE_FUNCTION_USER }}:${{ secrets.AZURE_FUNCTION_PASS }}" \
        --data-binary @functionapp.zip \
        "https://functionappsede.scm.azurewebsites.net/api/zipdeploy?isAsync=true&restart=true&clean=true"